user:
- id
- email
- hash_password
- is_admin
- latlon
- stripe_customer_id
- created_at
- modified_at

item:
- id
- name
- description
- category
- amount

cart:
- id
- user_id
- session_id
- created_at
- modified_at

cart_item:
- id
- cart_id
- item_id
- quantity

order:
- id
- user_id
- amount
- stripe_charge
- failure_message
- latlon
- created_at
- modified_at
- failed_at
- verified_at
- captured_at
- cooked_at
- delivered_at

order_item:
- id
- order_id
- item_id

email:
- id
- user_id
- recipient
- template
- props
- created_at
