version: '3.6'
services:
  dockerhost:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure

  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-alpha37
    ports:
      - "8080:8080"
    restart: always
    depends_on: [ dockerhost ]
    environment:
      HASURA_GRAPHQL_DATABASE_URL: "postgres://postgres:postgres@dockerhost:5432/${POSTGRES_DATABASE}"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console

      # HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"
      HASURA_GRAPHQL_ACCESS_KEY: "${HASURA_SECRET}"
      HASURA_GRAPHQL_AUTH_HOOK: "${HASURA_AUTH_WEBHOOK_URL}"

      CART_SCHEMA_URL: "${CART_SCHEMA_URL}"      

      CREATE_ORDER_WEBHOOK_URL: "${CREATE_ORDER_WEBHOOK_URL}"
      WAITER_WEBHOOK_URL: "${WAITER_WEBHOOK_URL}"
      CAPTURE_WEBHOOK_URL: "${CAPTURE_WEBHOOK_URL}"
      CHEF_WEBHOOK_URL: "${CAPTURE_WEBHOOK_URL}"
      DRIVER_WEBHOOK_URL: "${DRIVER_WEBHOOK_URL}"
      EMAIL_WEBHOOK_URL: "${EMAIL_WEBHOOK_URL}"
